module.exports = {
  Template: require('./Template'),
  addAttrs: require('./addAttrs'),
  addNonParamAttributes: require('./addNonParamAttributes'),
  addParamAttributes: require('./addParamAttributes'),
  addSignatureParams: require('./addSignatureParams'),
  addSignatureReturns: require('./addSignatureReturns'),
  addSignatureTypes: require('./addSignatureTypes'),
  attachModuleSymbols: require('./attachModuleSymbols'),
  buildAttrsString: require('./buildAttrsString'),
  buildItemTypeStrings: require('./buildItemTypeStrings'),
  buildMemberNav: require('./buildMemberNav'),
  buildNav: require('./buildNav'),
  createGenerate: require('./createGenerate'),
  convertHashToLink: require('./convertHashToLink'),
  generateSourceFiles: require('./generateSourceFiles'),
  getPathFromDoclet: require('./getPathFromDoclet'),
  getTutorialLink: require('./getTutorialLink'),
  linkToExternal: require('./linktoExternal'),
  needsSignature: require('./needsSignature'),
  shortenPaths: require('./shortenPaths'),
  splitJoinedArray: require('./splitJoinedArray'),
  updateItemName: require('./updateItemName'),
};
